### ISSUE TITLE
Application fails to load on second attempt, after a successful first attempt

### ISSUE THREAD

**Issue by TL41** [LeadingPointDev/waltz-dataloaders-lpl#1]
The data could have multiple records with the same asset_code. I think this is a valid case because other columns are different. I'm guessing this is in the expiration logic, where maybe we need to consider more fields than we currently do.

`19:39:56.237 [main] DEBUG org.jooq.impl.DefaultConnectionProvider - setting auto commit      : true
Exception in thread "main" org.jooq.exception.InvalidResultException: Key 213222 is not unique in Result for +----------+----+`

![image](https://github.com/LeadingPointDev/waltz-dataloaders-lpl/assets/59031582/3bcd2cf4-6e70-413b-8896-8859375b7018)
![image](https://github.com/LeadingPointDev/waltz-dataloaders-lpl/assets/59031582/adb143bd-fc98-4250-bf39-ba8a856d8604)

**Comment by OscarAgostic** [comment]
My understanding is that asset_code should be unique if used as external_id.
I think this is a problem with the data, rather than the loaders.
